version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: school_postgres
    environment:
      POSTGRES_DB: school_console_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 19
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: school_app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/school_console_app
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 19
    stdin_open: true
    tty: true

volumes:
  postgres_data:
